steps:
- name: gcr.io/cloud-builders/docker
  env:
    - DOCKER_BUILDKIT=1
  args:
    - build
    - -f
    - dockerfiles/drift_api.dockerfile
    - -t
    - gcr.io/dtu-mlops-data-482907/drift-api
    - .
images:
- gcr.io/dtu-mlops-data-482907/drift-api
