steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'dockerfiles/api.cloudrun.dockerfile'
      - '-t'
      - '${_IMAGE_NAME}'
      - '.'
    timeout: 1800s

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_IMAGE_NAME}'
    timeout: 600s

images:
  - '${_IMAGE_NAME}'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: 3600s
